### ISSUE TITLE
lines not rendered due to stroke-width set to 0

### ISSUE THREAD

**Issue by take4mats** [Seao/grav-plugin-diagrams#4]
I'm using v1.0.1 and found the example sequence diagram doesn't render lines and arrows correctly.
It seems applied CSS is below, around line 130 in `css/mermaid.css`.
```css
.grid path {
  stroke-width: 0;
}
```
When I set `stroke-width` to 1, it did render.  Is it a bug?
